# Generated by Django 5.1.7 on 2025-04-18 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_examinationschedule_exam_group'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamregistration',
            name='exam_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examinationgroup'),
            preserve_default=False,
        ),
    ]
