# Generated by Django 5.1.7 on 2025-04-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sudent_id',
            new_name='student_id',
        ),
    ]
