# Generated by Django 5.1.7 on 2025-04-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sudent_id_student_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Staff',
        ),
    ]
