# Generated by Django 5.1.7 on 2025-04-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staffrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_id',
            new_name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staffrole'),
        ),
    ]
