# Generated by Django 5.1.7 on 2025-04-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_teacher_id_staff_staff_id_staff_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='department_id',
        ),
    ]
