# Generated by Django 5.1.7 on 2025-04-04 15:50

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_department_staff_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/students_image'),
        ),
    ]
