# Generated by Django 5.1.7 on 2025-04-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_staffattendance_status_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_group_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examination',
            name='exam_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examinationgroup'),
        ),
    ]
