# Generated by Django 5.1.7 on 2025-04-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sessions_examination_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationschedule',
            name='exam_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examinationgroup'),
        ),
    ]
