# Generated by Django 5.1.7 on 2025-04-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_librarybookcategory_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarybookcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
